workflow:
  name: TodoApp Deployment
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^feature\/.*/'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always

variables:
  GIT_STRATEGY: fetch
  GIT_CLEAN_FLAGS: -ffdx -e !.gitignore
  NODE_VERSION: "18"
  NPM_CONFIG_CACHE: "/tmp/npm-cache"
  # Docker-specific global variables (non-sensitive)
  FRONTEND_IMAGE: $DOCKERHUB_USER/todo-app-frontend
  BACKEND_IMAGE: $DOCKERHUB_USER/todo-app-backend
  TAG: $CI_COMMIT_SHORT_SHA  # Tags with commit SHA for traceability;test alternative: $CI_PIPELINE_ID
  K8S_CONTEXT: kubernetes-the-hard-way
  K8S_NAMESPACE: todo-app
  K8S_MANIFEST_DIR: k8s/
  FULL_CONTEXT: "$CI_PROJECT_PATH:$K8S_CONTEXT" 

stages:
  - build
  - test
  - docker-build
  - docker-test
  - docker-push



#Cache template for reusability
.node_cache_template: &node_cache
  cache:
    key: ${CI_JOB_NAME}-${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
    policy: pull-push


before_script:
  #- apk add --no-cache bash curl git
  - rm -rf .tmp/ || true  # Target the problematic .tmp dir
  - rm -rf backend/node_modules frontend/node_modules || true
  - rm -rf frontend/dist || true
  - sleep 10
  - npm config set cache ${NPM_CONFIG_CACHE} --global
  - rm -rf $CI_PROJECT_DIR/*.tmp/ || true  # Safely remove temp dirs
build-frontend:
  stage: build
  image: node:${NODE_VERSION}-alpine
  resource_group: build
  tags:
    - macos
    - shell
  script: 
    - cd frontend
    - npm ci --cache ${NPM_CONFIG_CACHE}
    - npm run build
    - echo "Frontend build completed successfully"
  artifacts:
    when: on_success
    expire_in: "1 day"
    paths:
      - frontend/dist/
  cache:
    key: frontend-${CI_COMMIT_REF_SLUG}
    paths:
      - frontend/node_modules/
    policy: pull-push
  
build-backend:
  stage: build
  image: node:${NODE_VERSION}-alpine
  resource_group: build
  needs:
    - build-frontend
  tags:
    - macos
    - shell
  before_script:
    - rm -rf frontend/ backend/node_modules || true  
  script: 
    - cd backend
    - npm ci --cache ${NPM_CONFIG_CACHE}
    - echo "Backend dependencies installed successfully"
    # Add any backend build steps if needed
  artifacts:
    when: on_success
    expire_in: "1 day"
    paths:
      - backend/
    exclude:
      - backend/node_modules/
  cache:
    key: backend-${CI_COMMIT_REF_SLUG}
    paths:
      - backend/node_modules/
    policy: pull

test-frontend:
  stage: test
  image: node:${NODE_VERSION}-alpine
  tags:
    - macos
    - shell
  dependencies:
    - build-frontend
  script:
    - cd frontend
    - npm ci --cache ${NPM_CONFIG_CACHE}
    - npm run test:ci
  artifacts:
    when: always
    expire_in: "1 week"
    paths:
      - frontend/coverage/
    reports:
      coverage_report:
        coverage_format: cobertura
        path: frontend/coverage/cobertura-coverage.xml
  cache:
    key: frontend-${CI_COMMIT_REF_SLUG}
    paths:
      - frontend/node_modules/
    policy: pull
  coverage: '/Lines\s*:\s*(\d+\.?\d*)%/'
  allow_failure: true

test-backend:
  stage: test
  image: node:${NODE_VERSION}-alpine
  needs:
    - build-backend
  tags:
    - macos
    - shell
  dependencies:
    - build-backend
  script:
    - cd backend
    - npm ci --cache ${NPM_CONFIG_CACHE}
    - npm run test:ci 
    - sleep 20
  artifacts:
    when: always
    expire_in: "1 week"
    paths:
    - backend/junit.xml
    - backend/coverage/
    reports:
      junit: backend/junit.xml
      coverage_report:
        coverage_format: cobertura
        path: backend/coverage/cobertura-coverage.xml
  cache:
    key: backend-${CI_COMMIT_REF_SLUG}
    paths:
      - backend/node_modules/
    policy: pull
  coverage: '/Lines\s*:\s*(\d+\.?\d*)%/'
  retry: 2

docker-build-frontend:
  stage: docker-build
  tags:
    - macos
    - shell
  before_script:
    - echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin
  script:
    - docker build -t $FRONTEND_IMAGE:$TAG frontend/ || { echo "Frontend build failed"; exit 1; }   # Build with SHA tag; added error handling
    - if [ "$CI_COMMIT_BRANCH" == "main" || "$CI_COMMIT_BRANCH" =~ '/^feature\/.*/' ]; then docker tag $FRONTEND_IMAGE:$TAG $FRONTEND_IMAGE:latest; fi 
  needs:
    - build-frontend
  dependencies:
    - build-frontend
  retry: 2

docker-build-backend:
  stage: docker-build
  tags:
    - macos
    - shell
  before_script:
    - echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin
  script:
    - docker build -t $BACKEND_IMAGE:$TAG backend/ || { echo "Backend build failed"; exit 1; }  # Build with SHA tag; added error handling
    - if [ "$CI_COMMIT_BRANCH" == "main" || "$CI_COMMIT_BRANCH" =~ '/^feature\/.*/' ]; then docker tag $BACKEND_IMAGE:$TAG $BACKEND_IMAGE:latest; fi 
  needs:
    - build-backend
  dependencies:
    - build-backend
  retry: 2
